### ISSUE TITLE
Installing ChoroplethMaps

### ISSUE THREAD

**Issue by luiarthur** [penntaylor/ChoroplethMaps.jl#1] opened 2016-05-01 05:14 UTC
Hi. Thanks for the nice package. Quick note: When I was installing ChoroplethMaps, I ran into a missing dependency -- `ZipFile`. And for some reason I had to build the Proj4 package? I suggest adding this to **Install** section:

``` julia
Pkg.clone("https://github.com/FugroRoames/Proj4.jl.git")
Pkg.clone("https://github.com/penntaylor/DBaseReader.jl.git")
Pkg.clone("https://github.com/penntaylor/ChoroplethMaps.jl.git")
Pkg.add("ZipFile")
Pkg.build("Proj4")
```

Also, when I tried your example, I got this error

> julia> choroplethmap(mapify(df, Provider.STATESUMMARY(), key=:NAME), group=:NAME, color=:PCT)
> ERROR: MethodError: `convert` has no method matching convert(::Type{Gadfly.Guide.Annotation}, ::Compose.Context, ::Gadfly.Guide.UnderGuidePosition)
> This may have arisen from a call to the constructor Gadfly.Guide.Annotation(...),
> since type constructors fall back to convert methods.
> Closest candidates are:
> Gadfly.Guide.Annotation(::Compose.Context)
> Gadfly.Guide.Annotation(::Any)
> call{T}(::Type{T}, ::Any)
>  ...
> in choroplethmap at /home/luiarthur/.julia/v0.4/ChoroplethMaps/src/ChoroplethMaps.jl:112

A missing plotting library perhaps? I was able to run the example with Gadfly though. I was using `julia version 0.4.5`.

Thanks.

**Comment by penntaylor** [comment] 2016-05-05 17:44
Thanks for bringing these issues to my attention. I'll look into the installation issue. You shouldn't have had to explicitly build Proj4, so either ChoroplethMaps has gotten out of sync with it, or I introduced a regression somewhere.

The Gadfly error you mention happens because I mistakenly committed a feature branch to master. I'll get this cleaned up within a few days.

**Comment by penntaylor** [comment] 2016-05-05 23:46
Arthur, pull down the master branch again and the first example should no longer give that error. The graticule is unfortunately not in the canonical "below map" position yet, but can be turned off entirely by passing `graticule=false` into the call to `choroplethmap`.

**Closed as completed by penntaylor** 2016-05-05 23:46 UTC
